### ISSUE TITLE
JwtStrategy requires a secret or key

### ISSUE THREAD

**Issue by jongunnar0210** [thisismydesign/nestjs-starter#10]
Hi, I cloned the repository and ran yarn and then yarn start and then I got this error:

$ yarn start
yarn run v1.22.10
$ nest start
[Nest] 11572   - 23.06.2021, 16:57:06   [NestFactory] Starting Nest application...
[Nest] 11572   - 23.06.2021, 16:57:06   [InstanceLoader] ServerModule dependencies initialized +32ms
[Nest] 11572   - 23.06.2021, 16:57:06   [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 11572   - 23.06.2021, 16:57:06   [InstanceLoader] PassportModule dependencies initialized +1ms
[Nest] 11572   - 23.06.2021, 16:57:06   [InstanceLoader] AuthModule dependencies initialized +0ms
[Nest] 11572   - 23.06.2021, 16:57:06   [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 11572   - 23.06.2021, 16:57:06   [InstanceLoader] ConsoleModule dependencies initialized +0ms
[Nest] 11572   - 23.06.2021, 16:57:06   [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 11572   - 23.06.2021, 16:57:06   [ExceptionHandler] JwtStrategy requires a secret or key +32ms
TypeError: JwtStrategy requires a secret or key

**Comment by thisismydesign** [comment]
Follow the Usage instructions in the readme. Let me know if you still have the issue that way.
