### ISSUE TITLE
Amazon Cognito error 

### ISSUE THREAD

**Issue by SergioSuarezDev** [thisismydesign/nestjs-starter#13]
I have this error trying to use Amazon Cognito 

web_1  |     at Generator.next (<anonymous>)
web_1  |     at /app/node_modules/@nestjs/passport/dist/auth.guard.js:20:71
web_1  |     at new Promise (<anonymous>)
web_1  | [Nest] 137   - 09/15/2021, 3:26:51 PM   [ExceptionsHandler] unauthorized_client +7991ms
**web_1  | AuthorizationError: unauthorized_client**
web_1  |     at CognitoOauthStrategy.OAuth2Strategy.authenticate (/app/node_modules/passport-oauth2/lib/strategy.js:137:25)

in my env I have all configured params

DATABASE_URL=postgres://postgres:@db:5432
JWT_SECRET=secret
JWT_EXPIRES_IN=10d
**OAUTH_COGNITO_ID=xxxxxxxxx
OAUTH_COGNITO_SECRET=xxxxxxxxx
OAUTH_COGNITO_REDIRECT_URL=http://localhost:3000/auth/cognito/redirect
OAUTH_COGNITO_DOMAIN=my-app
OAUTH_COGNITO_REGION=eu-central-1**
OAUTH_GOOGLE_ID=id
OAUTH_GOOGLE_SECRET=secret
OAUTH_GOOGLE_REDIRECT_URL=http://localhost:3000/auth/google/redirect

What I can be doing wrong?

**Comment by SergioSuarezDev** [comment]
here my cognito app config

![Captura de pantalla 2021-09-15 a las 17 31 59](https://user-images.githubusercontent.com/3636232/133463671-6e356fd5-06a2-4a63-84c6-0447c6e904f5.png)

**Comment by thisismydesign** [comment]
Use stackoverflow for support questions, there are also google results related to this and i'm a lof of AWS resources can help set you up as well.
