### ISSUE TITLE
Unable to load video from nextjs /public folder

### ISSUE THREAD

**Issue by kylebaskin** [thisismydesign/nestjs-starter#17]
I ran into this problem as I was trying to upload a background video for my website.

Using a typical `<video src="/videos/video.webm"></video>` on my home page component does not load in the video, even though I can load images in from the same directory using the public directory in my root nextjs folder and the NextJS `<Image/>` component (as stated in a previous issue, you can't load in a plain `<img/>` in with this repo. I suspect it has something to do with the build process omitting non jsx components, but I'm still pretty new to this so I could be way off).

In order to get around this issue, I've found this solution - use the [next-videos npm package.](https://www.npmjs.com/package/next-videos). 

Here are the changes I had to make to get this to work:

next.config.js
```
const withVideos = require('next-videos')

module.exports = withVideos({
  distDir: '../../.next',
});
```

page.tsx
```
import React from 'react';
import { NextPage } from 'next';

import styles from '../styles/Home.module.css';

const Index: NextPage<{ data: string }> = (props) => {
  const { data } = props;

  return (
    <div className={styles.container}>
      <div className={styles.hero}>
        <video src={require('../public/videos/video.webm')} autoPlay muted></video>
      </div>
    </div>
  );
};

export default Index;
```

Hope this helps somebody.

**Comment by nynevi** [comment]
```
 // const {join} = require('path');

  @Get('videos/*')
  public async videos(@Req() req: Request, @Res() res: Response) {
    const parsedUrl = parse(req.url, true);
    const filePath = join(
      __dirname,
      '../../src/client/public', //matches this project's structure
      parsedUrl.pathname,
    );
    await this.viewService.getNextServer().serveStatic(req, res, filePath);
  }
```

**Comment by thisismydesign** [comment]
Hey @kylebaskin, can you check if @nynevi's solution work for you? I also recently updated all dependencies, so there might be new/easier ways to do this with Next. Please take a look. Closing for now, will reopen if it still doesn't work.

**Comment by Kyle1297** [comment]
I've noticed that none of my public files in next are being rendered, including images, sitemaps, etc. The above solutions have not worked for me. Any other potential options out there?

**Comment by thisismydesign** [comment]
@Kyle1297 do you have a route set up on the backend?

**Comment by Kyle1297** [comment]
Hey @thisismydesign, yeah I did. I followed @nynevi solution. Regardless, I found an alternative and rather simple solution, which is working wonderfully.

1. Placed my public folder in 'src/client'
2. Adjusted the nest-cli.json file to compile the assets (see below). This caused the public folder to be placed inside 'dist' on build.

```
{
  "collection": "@nestjs/schematics",
  "sourceRoot": "src/server",
  "compilerOptions": {
    "assets": [
      {
        "include": "../client/public/**/*",
        "watchAssets": true
      }
    ]
  }
}
```

4. Added useStaticAssets to the main.ts file (see below). You'll need to add <NestExpressApplication> for typescript to work.

```
async function bootstrap() {
  const app = await NestFactory.create<NestExpressApplication>(ServerModule);

  app.useStaticAssets(join(__dirname, '..', '..', 'public'));
	
  ...
}
bootstrap();
```

6. Then I just ran the build and it worked on both local and production.

Hope this helps!
