### ISSUE TITLE
On refresh of routes apart from index i get  a 404

### ISSUE THREAD

**Issue by Goochie** [thisismydesign/nestjs-starter#18]
First of all thank you for this project as its has saved me a lot of a time and i have learnt a lot from it.

That being said i just cannot figure out to ...

1. Avoid a 404 when i refresh on any route apart from /index ... i understand   @Get('_next*') captures next routes etc but when we refresh the browser is there any way to avoid the 404

2. As a fall-back if i get a 404 how do i redirect to /index

**Comment by kylebaskin** [comment]
Can you add your view.controller.ts file here? I believe I can help.

**Comment by thisismydesign** [comment]
@Goochie I couldn't reproduce this. For example, I can refresh `/home`. Please provide more details if this issue still exists for you.
