### ISSUE TITLE
Deployment to Heroku Not Working

### ISSUE THREAD

**Issue by qarthandgi** [thisismydesign/nestjs-starter#19]
Following up on my [previous issue](https://github.com/thisismydesign/nestjs-starter/issues/14), I'm now seeing a Heroku deployments failing for another reason. It seems that the use of decorators is throwing Heroku off and it doesn't know what to do with it.

Is there a Typescript config or something that needs to be set during deployment @thisismydesign?

![Screen Shot 2021-11-29 at 6 45 39 AM](https://user-images.githubusercontent.com/25380187/143870782-5ba7454e-e256-4ff2-a356-50fe8bd7e2e5.png)

**Comment by thisismydesign** [comment]
@qarthandgi If I use the `Deploy to Heroku` button in the readme it works fine. Seems like the issue is with a file that was created by you so I can't really help there.
