### ISSUE TITLE
Tailwind does not read the configuration file in the development environment

### ISSUE THREAD

**Issue by marcin-stasiak** [thisismydesign/nestjs-starter#20]
In production, the build process is run on the ./src/client directory, but while development, tailwind looks for a configuration file in the root of the project ./. So I have to create two almost identical configuration files or import betwen those files. 

Do you have a solution for this?

**Comment by thisismydesign** [comment]
Hey, not sure how to address this from our side, please open a support request to tailwind. It's quite a common use case to have the location of the config file configurable, probably also for monorepos.

Closing, but feel free to discuss on this thread.

**Comment by waaverecords** [comment]
Have you found an elegant solution?
Or the only option is to copy tailwind.config.js to the root.

**Comment by marcin-stasiak** [comment]
@waaverecords https://github.com/marcin-stasiak/full-stack-starter

**Comment by thisismydesign** [comment]
@marcin-stasiak Glad to see you found a solution. Is this something you would be up for adding to this project? If so, a PR is very welcome.

**Comment by Kyle1297** [comment]
Not sure if this is a better solution but I used tailwind presets to solve this issue. You still need two tailwind.config.js files but all of its content can basically be stored in a preset file that both config files inherit. Check the tailwind docs for reference: https://tailwindcss.com/docs/presets
