### ISSUE TITLE
Database does not exist

### ISSUE THREAD

**Issue by tal32123** [thisismydesign/nestjs-starter#22]
I downloaded the code and ran as it said in the docs and get the following error, I appreciate the help:

psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  database "database" does not exist

**Comment by thisismydesign** [comment]
You need to provide more context, such as the exact command and output. You can see that the same code runs fine [in the CI](https://github.com/thisismydesign/nestjs-starter/blob/2f92842c8d3eb1e230fae1041ef95b499493151a/.github/workflows/ci.yml) so this is very likely an issue on your side. Closing for now.
