### ISSUE TITLE
Cannot start dev server

### ISSUE THREAD

**Issue by niteshbalusu11** [thisismydesign/nestjs-starter#41]
Hello!

I am unable to get this to work for some reason:
I see that when you do `yarn start:dev` or `yarn start` it seems to be looking for `dist/main` which does not exist for me, whenever I am building I am only getting the following folders inside the dist directory. I am not sure what I am missing.

<img width="339" alt="Screen Shot 2022-06-07 at 5 35 11 PM" src="https://user-images.githubusercontent.com/84944042/172486865-b8d3fbc2-3956-4cdd-b6bc-1860a4a5cef2.png">

**Comment by niteshbalusu11** [comment]
It throws the following error:

```
Error: Cannot find module '....with-electron-typescript-app/dist/main'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by thisismydesign** [comment]
Hey, are you running through Docker? It pretty much does `yarn install` and `yarn start:dev`. What commands are you running exactly?

**Comment by niteshbalusu11** [comment]
I had to copy-paste instead of directly using the template, maybe that messed up something.
However, if I am using the template itself, it's throwing these graphQL errors.


```
node_modules/@nestjs/graphql/dist/interfaces/gql-gateway-module-options.interface.d.ts:1:58 - error TS2307: Cannot find module '@apollo/gateway' or its corresponding type declarations.

1 import { GatewayConfig, ServiceEndpointDefinition } from '@apollo/gateway';
                                                           ~~~~~~~~~~~~~~~~~

node_modules/@nestjs/graphql/dist/interfaces/gql-gateway-module-options.interface.d.ts:2:35 - error TS2307: Cannot find module '@apollo/gateway/src/datasources/types' or its corresponding type declarations.

2 import { GraphQLDataSource } from '@apollo/gateway/src/datasources/types';
```

**Comment by thisismydesign** [comment]
I still don't know what you're doing exactly. I can bring the project up & build it as well without any errors. It also works in the CI.

**Comment by niteshbalusu11** [comment]
Weird, I just cloned, installed dependencies, and started the dev server and it gives me those graphQL errors.

**Comment by thisismydesign** [comment]
Got the same error when running outside of docker but works fine within docker. Someone else mentioned that the same errors went away when updating dependencies: https://github.com/thisismydesign/nestjs-starter/pull/31 I'm working on updating those at the moment, so should hopefully be resolved soon. But in any case, the docker setup is the supported one.

**Comment by niteshbalusu11** [comment]
Yeah, I just did `yarn upgrade --latest` just to try it out, which seems to have fixed the issue.
