### ISSUE TITLE
Cyprus container not working on arm64 architecture.

### ISSUE THREAD

**Issue by kevinwheeler** [thisismydesign/nestjs-starter#460]
Tried to run `docker run -it -v $PWD:/e2e -w /e2e --entrypoint=cypress cypress/included:10.0.3 run --config-file cypress.docker.config.ts` as per the README.

Encountered:
```
Status: Downloaded newer image for cypress/included:10.0.3
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
The Test Runner unexpectedly exited via a close event with signal SIGSEGV
```

**Comment by thisismydesign** [comment]
@kevinwheeler Thanks for reporting it. The readme was outdated, the project already uses cypress v12 which is compatible with amd64. Updated the command to: `docker run -it -v $PWD:/e2e -w /e2e --network="host" --entrypoint=cypress cypress/included:12.2.0 run`
