### ISSUE TITLE
[Feature request] - Package app into an executable

### ISSUE THREAD

**Issue by niteshbalusu11** [thisismydesign/nestjs-starter#49]
Hello!

I was wondering if there is a way to package a nest/next app with https://github.com/vercel/pkg

Since both are served with a single server, maybe there is a way to build an executable? I tried looking into it but failed. Was wondering if you had any idea about this.

**Comment by thisismydesign** [comment]
Hey, no clue, sorry.

Closing as no support for this is planned.
