### ISSUE TITLE
Unexpected character '�' when importing images

### ISSUE THREAD

**Issue by vitordhers** [thisismydesign/nestjs-starter#6]
Cant import images from my assets folder. It is inside client folder. I get this stupid webpack error:

`./assets/img/logo.png
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)`

I've also added my assets folder to `tsconfig.json` (inside client) Added this code inside `next-env.d.ts` from stackoverflow:

```
declare module "*.png" {
  const value: any;
  export = value;
}
```
It stops IDE from showing errors in the file but still I can't run the code. Any idea?

Thanks in advance.

**Comment by thisismydesign** [comment]
I've seen the same error. I think there are a few different solutions but I ended up using `next/image` instead of importing the image, like so:

```js
import Image from 'next/image';

<Image src="/logo-45x45.png" />
```

The image is in `scr/client/public/logo-45x45.png`.

**Comment by vitordhers** [comment]
Thanks, I overlooked that in my project.
